<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LongMaidDisplayPlugin</AssemblyName>
    <RootNamespace>LongMaidDisplayPlugin</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutDir>$(MSBuildProjectDirectory)\..\..\config\plugins\龙女仆\</OutDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SnakeTail.csproj" />
  </ItemGroup>
</Project>
